/* ─────────────────────────────────────────────────────────────────────────
   PREGUNTAS_NACIONALIDAD — Manual de preparación de la prueba CCSE 2026
   Instituto Cervantes · 300 preguntas oficiales · 5 tareas

   Preguntas, opciones y respuestas transcritas literalmente del manual
   oficial. La respuesta correcta (campo c) sale de la tabla de Soluciones
   del propio manual (págs. 99-102).

   Tarea 2 (Verdadero/Falso) lleva dos campos añadidos:
     vf   — true si la afirmación es verdadera, false si es falsa
     corr — cómo es en realidad, según el artículo del temario del manual
   ───────────────────────────────────────────────────────────────────────── */

window.TEMAS_NAC = {
  tarea1: 'Gobierno, legislación y participación ciudadana',
  tarea2: 'Derechos y deberes fundamentales',
  tarea3: 'Organización territorial de España. Geografía física y política',
  tarea4: 'Cultura e historia de España',
  tarea5: 'Sociedad española'
};

window.PREGUNTAS_NAC = [

  /* ── TAREA1: Gobierno, legislación y participación ciudadana (120 preguntas) ── */

  { id:'n1001', tema:'tarea1', p:'España es…', o:['una monarquía parlamentaria.','una república federal.','una monarquía federal.'], c:0 },
  { id:'n1002', tema:'tarea1', p:'La ley fundamental de España se llama…', o:['Constitución.','Ley básica.','Ordenamiento esencial.'], c:0 },
  { id:'n1003', tema:'tarea1', p:'Según la Constitución española, la soberanía nacional reside en…', o:['el pueblo español.','el Gobierno del Estado.','el Congreso de los Diputados.'], c:0 },
  { id:'n1004', tema:'tarea1', p:'El Instituto de las Mujeres es…', o:['una institución europea.','un organismo español.','una ONG.'], c:1 },
  { id:'n1005', tema:'tarea1', p:'¿Cuándo puedo hacer los trámites en la sede electrónica?', o:['En cualquier horario.','Únicamente por la mañana.','De lunes a viernes.'], c:0 },
  { id:'n1006', tema:'tarea1', p:'El castellano o español es lengua oficial…', o:['en toda España.','solo donde no hay otras lenguas.','en toda la península ibérica.'], c:0 },
  { id:'n1007', tema:'tarea1', p:'¿Cuál de estas fuerzas de seguridad es de ámbito autonómico?', o:['Policía local.','Guardia Civil.','Policía Foral de Navarra.'], c:2 },
  { id:'n1008', tema:'tarea1', p:'¿Qué fuerza de seguridad está en toda España?', o:['La Policía Foral de Navarra.','El Cuerpo Nacional de Policía.','Los Mossos d’Esquadra.'], c:1 },
  { id:'n1009', tema:'tarea1', p:'En la Constitución se establece la separación de poderes: el poder ejecutivo, el legislativo y el…', o:['judicial.','informativo.','político.'], c:0 },
  { id:'n1010', tema:'tarea1', p:'La bandera de España debe utilizarse…', o:['solo los días de fiesta oficial.','en todos los edificios públicos.','solo en actos del Gobierno español.'], c:1 },
  { id:'n1011', tema:'tarea1', p:'¿Quién es el jefe del Estado en España?', o:['El presidente del Gobierno.','El rey.','El ministro de Economía.'], c:1 },
  { id:'n1012', tema:'tarea1', p:'La gestión de la sanidad es competencia de…', o:['el Estado.','las comunidades autónomas.','los ayuntamientos.'], c:1 },
  { id:'n1013', tema:'tarea1', p:'¿Quién fue el primer presidente del Gobierno de España en democracia?', o:['Mariano Rajoy.','Adolfo Suárez.','José Luis Rodríguez Zapatero.'], c:1 },
  { id:'n1014', tema:'tarea1', p:'¿Cuál de estos organismos se encarga de interpretar la Constitución?', o:['El Poder Constitucional.','El Tribunal Constitucional.','El Consejo General del Poder Judicial.'], c:1 },
  { id:'n1015', tema:'tarea1', p:'¿Quién modera el funcionamiento de las instituciones españolas?', o:['El presidente del Gobierno.','El rey.','El director de la Real Academia Española.'], c:1 },
  { id:'n1016', tema:'tarea1', p:'¿Cómo se llama la cámara de representación territorial en España?', o:['Senado.','Diputación permanente.','Congreso de los Diputados.'], c:0 },
  { id:'n1017', tema:'tarea1', p:'¿Qué se necesita para hacer trámites por internet con la Administración?', o:['Un pasaporte válido.','Una firma electrónica.','Una firma en papel.'], c:1 },
  { id:'n1018', tema:'tarea1', p:'¿Cómo se aprobó la Constitución?', o:['Por imposición legal.','Por referéndum.','Por el Tribunal Constitucional.'], c:1 },
  { id:'n1019', tema:'tarea1', p:'¿Cómo se llama la ley más importante de cada comunidad autónoma?', o:['Estatuto de Autonomía.','Normativa autonómica.','Ley de la comunidad.'], c:0 },
  { id:'n1020', tema:'tarea1', p:'Las instalaciones culturales y deportivas públicas son competencia del…', o:['Ayuntamiento.','Ministerio de Educación, Formación Profesional y Deportes.','Ministerio de Igualdad.'], c:0 },
  { id:'n1021', tema:'tarea1', p:'¿Quién dirige la administración militar de España?', o:['Los ayuntamientos.','El Gobierno.','Las Cortes Generales.'], c:1 },
  { id:'n1022', tema:'tarea1', p:'¿Qué hay en las Islas Baleares, en vez de diputaciones?', o:['Cabildos.','Consejos insulares.','Centros de diputados.'], c:1 },
  { id:'n1023', tema:'tarea1', p:'¿Qué ciudad tiene más habitantes?', o:['Sevilla.','Barcelona.','Zaragoza.'], c:1 },
  { id:'n1024', tema:'tarea1', p:'Las Cortes Generales representan…', o:['al pueblo español.','a los partidos políticos.','a los ministros.'], c:0 },
  { id:'n1025', tema:'tarea1', p:'El Congreso de los Diputados y el Senado constituyen el poder…', o:['ejecutivo.','legislativo.','judicial.'], c:1 },
  { id:'n1026', tema:'tarea1', p:'¿Cómo pueden los ciudadanos proponer nuevas leyes al Congreso?', o:['Reuniendo 500 000 firmas.','Solicitándolo al rey.','Creando una asociación.'], c:0 },
  { id:'n1027', tema:'tarea1', p:'¿Cuántas comunidades autónomas hay en España?', o:['8.','17.','25.'], c:1 },
  { id:'n1028', tema:'tarea1', p:'Los colores de la bandera española son…', o:['blanco y rojo.','rojo y amarillo.','amarillo y blanco.'], c:1 },
  { id:'n1029', tema:'tarea1', p:'¿Dónde está la sede del Gobierno de España?', o:['En Madrid.','En Barcelona.','En Sevilla.'], c:0 },
  { id:'n1030', tema:'tarea1', p:'La bandera azul con 12 estrellas amarillas en círculo es la bandera de…', o:['la Unión Europea.','el Parlamento Europeo.','la Comisión de Europa.'], c:0 },
  { id:'n1031', tema:'tarea1', p:'En las elecciones municiales se vota a…', o:['alcaldes y concejales','ministros y ministras.','diputados y senadores.'], c:0 },
  { id:'n1032', tema:'tarea1', p:'¿Qué lengua es oficial en el País Vasco?', o:['El bable.','El aragonés.','El euskera.'], c:2 },
  { id:'n1033', tema:'tarea1', p:'Todos los españoles tienen el deber de conocer la lengua…', o:['autonómica del Estado.','oficial del Estado.','local del Estado.'], c:1 },
  { id:'n1034', tema:'tarea1', p:'El aranés es una lengua cooficial que se habla en un pequeño territorio de…', o:['Cataluña.','La Rioja.','Aragón.'], c:0 },
  { id:'n1035', tema:'tarea1', p:'Las instituciones de una comunidad autónoma son: el consejo de gobierno, el presidente y…', o:['el ayuntamiento.','la asamblea legislativa.','la delegación de gobierno.'], c:1 },
  { id:'n1036', tema:'tarea1', p:'¿Cuál de estas opciones es una lengua cooficial en alguna comunidad autónoma?', o:['El gallego.','El aragonés.','El murciano.'], c:0 },
  { id:'n1037', tema:'tarea1', p:'¿Qué institución tiene como fin la promoción de la enseñanza de la lengua española y la difusión de la cultura en español?', o:['El Instituto Nacional de Administración Pública.','El Instituto Nacional de Estadística.','El Instituto Cervantes.'], c:2 },
  { id:'n1038', tema:'tarea1', p:'¿Cuál de los siguientes organismos trabaja para conseguir la normalización lingüística?', o:['El Institut Ramon Llull.','El Instituto Cervantes.','La Real Academia Española.'], c:2 },
  { id:'n1039', tema:'tarea1', p:'¿Dónde vive el presidente del Gobierno?', o:['En el Palacio Real.','En el Palacio de la Zarzuela.','En el Palacio de la Moncloa.'], c:2 },
  { id:'n1040', tema:'tarea1', p:'¿Cuál de los siguientes cuerpos forma parte de las Fuerzas Armadas de España?', o:['La Policía Foral.','La Guardia Civil.','El Ejército del Aire.'], c:2 },
  { id:'n1041', tema:'tarea1', p:'¿Quiénes forman parte del Gobierno?', o:['Los ministros.','Los concejales.','Los alcaldes.'], c:0 },
  { id:'n1042', tema:'tarea1', p:'España es un…', o:['estado social y democrático de Derecho.','estado libre asociado.','estado confederado.'], c:0 },
  { id:'n1043', tema:'tarea1', p:'¿Cuál de las siguientes siglas corresponde a un partido político?', o:['PP.','PIB.','UE.'], c:0 },
  { id:'n1044', tema:'tarea1', p:'¿Qué título tiene la futura reina, hija del rey?', o:['Princesa de Asturias.','Princesa de Aragón.','Duquesa de Alba.'], c:0 },
  { id:'n1045', tema:'tarea1', p:'¿Con qué rey se restaura la democracia en España después del régimen de Franco?', o:['Con Carlos III.','Con Alfonso XIII.','Con Juan Carlos I.'], c:2 },
  { id:'n1046', tema:'tarea1', p:'¿En qué año se aprobó la Constitución española?', o:['En 1957.','En 1978.','En 2001.'], c:1 },
  { id:'n1047', tema:'tarea1', p:'¿Cuántas comunidades autónomas tienen su propia bandera?', o:['Ninguna.','Todas.','Las que tienen una lengua cooficial.'], c:1 },
  { id:'n1048', tema:'tarea1', p:'¿Qué organismo oficial atiende las quejas de los ciudadanos por el mal funcionamiento de las administraciones?', o:['La Oficina de Atención al Consumidor.','La Policía Nacional.','El Defensor del Pueblo.'], c:2 },
  { id:'n1049', tema:'tarea1', p:'¿Cuántas firmas, como mínimo, deben recoger los ciudadanos para poder presentar una proposición de ley?', o:['250 000.','100 000.','500 000.'], c:2 },
  { id:'n1050', tema:'tarea1', p:'¿A cuál de las siguientes organizaciones internacionales pertenece España?', o:['Comunidad de Estados Independientes (CEI).','Fondo Monetario Internacional (FMI).','Unión Económica Euroasiática (UEE).'], c:1 },
  { id:'n1051', tema:'tarea1', p:'En la organización de la Administración se distinguen tres niveles: central, autonómica y…', o:['estatal.','regional.','local.'], c:2 },
  { id:'n1052', tema:'tarea1', p:'El poder legislativo corresponde...', o:['al presidente y los ministros.','a los jueces y magistrados.','a los diputados y senadores.'], c:2 },
  { id:'n1053', tema:'tarea1', p:'¿Dónde vive el rey?', o:['En el Palacio de la Moneda.','En el Palacio de la Zarzuela.','En el Palacio de la Moncloa.'], c:1 },
  { id:'n1054', tema:'tarea1', p:'El nombre oficial del parlamento español es…', o:['Cortes Generales.','Congreso de los Diputados.','Senado.'], c:0 },
  { id:'n1055', tema:'tarea1', p:'El Instituto de Comercio Exterior de España, el Instituto de las Mujeres y la Dirección General de Tráfico…', o:['son organismos autónomos.','dependen de ministerios.','son organismos internacionales.'], c:1 },
  { id:'n1056', tema:'tarea1', p:'¿Quién puede reinar en España?', o:['Solo los hombres.','Solo las mujeres.','Tanto los hombres como las mujeres.'], c:2 },
  { id:'n1057', tema:'tarea1', p:'El Tribunal de Cuentas depende de…', o:['la Presidencia del Gobierno.','las Cortes Generales.','el Ministerio de Hacienda.'], c:1 },
  { id:'n1058', tema:'tarea1', p:'¿Quién es la tercera autoridad del Estado, después del rey y el presidente del Gobierno?', o:['El presidente del Senado.','El ministro de Economía.','El presidente del Congreso de los Diputados.'], c:2 },
  { id:'n1059', tema:'tarea1', p:'¿Qué lengua cooficial se habla en las Islas Baleares?', o:['Gallego.','Catalán.','Euskera.'], c:1 },
  { id:'n1060', tema:'tarea1', p:'La Constitución defiende valores tales como la libertad, la igualdad, el pluralismo político y…', o:['la justicia.','la solidaridad.','la fraternidad.'], c:0 },
  { id:'n1061', tema:'tarea1', p:'Cuando una ley ya está aprobada, ¿qué necesita para poder aplicarse?', o:['Nada.','Normas que la desarrollen.','Ser revisada por el Parlamento.'], c:1 },
  { id:'n1062', tema:'tarea1', p:'¿Cuántos habitantes hay en España?', o:['95 millones.','49 millones.','67 millones.'], c:1 },
  { id:'n1063', tema:'tarea1', p:'¿Cuál de estos es un órgano consultivo del Gobierno de España?', o:['El Parlamento Europeo.','El Consejo de Estado.','El Tribunal Constitucional.'], c:1 },
  { id:'n1064', tema:'tarea1', p:'¿Quién dirige la política interior y exterior de España?', o:['El rey.','El Gobierno.','El Congreso de los Diputados.'], c:1 },
  { id:'n1065', tema:'tarea1', p:'El Defensor del Pueblo depende de…', o:['el Consejo de Ministros.','el Tribunal de Cuentas.','las Cortes Generales.'], c:2 },
  { id:'n1066', tema:'tarea1', p:'El Instituto Etxepare tiene como misión la difusión del…', o:['euskera y la cultura vasca.','bable y la cultura cántabra.','gallego y la cultura galaica.'], c:0 },
  { id:'n1067', tema:'tarea1', p:'¿Cuál de estas ciudades se encuentra entre las 10 más pobladas de España?', o:['Cádiz.','Málaga.','Albacete.'], c:1 },
  { id:'n1068', tema:'tarea1', p:'¿Quién puede realizar trámites en línea ante la Administración Pública?', o:['Jueces y magistrados.','Cualquier ciudadano.','Abogados colegiados.'], c:1 },
  { id:'n1069', tema:'tarea1', p:'¿Cómo se llama el rey de España?', o:['Juan Carlos I.','Felipe VI.','Alfonso XIII.'], c:1 },
  { id:'n1070', tema:'tarea1', p:'¿Cómo se llama el órgano de gobierno de los jueces y magistrados?', o:['Tribunal Supremo.','Consejo General del Poder Judicial.','Consejo de Estado.'], c:1 },
  { id:'n1071', tema:'tarea1', p:'¿Quién aprueba los presupuestos generales del Estado?', o:['Las Cortes Generales.','El Tribunal de Cuentas.','El Gobierno de España.'], c:0 },
  { id:'n1072', tema:'tarea1', p:'La Constitución española es…', o:['la ley fundamental.','parte de otra ley.','una ley secundaria.'], c:0 },
  { id:'n1073', tema:'tarea1', p:'Las Cortes Generales están compuestas por el Senado y…', o:['el Congreso de los Diputados.','el Tribunal Supremo.','el Consejo de Estado.'], c:0 },
  { id:'n1074', tema:'tarea1', p:'¿Quién elabora las leyes?', o:['El poder ejecutivo.','El poder legislativo.','El poder judicial.'], c:1 },
  { id:'n1075', tema:'tarea1', p:'La defensa de la integridad territorial de España corresponde a…', o:['la Policía Nacional y la Guardia Civil.','las Fuerzas Armadas.','la Policía Nacional y las policías autonómicas.'], c:1 },
  { id:'n1076', tema:'tarea1', p:'El Ejército español participa desde 1989 en misiones de paz de la…', o:['Organización de Estados Iberoamericanos (OEI).','Unión Europea Occidental (UEO).','Organización de las Naciones Unidas (ONU).'], c:2 },
  { id:'n1077', tema:'tarea1', p:'¿Quién vigila puertos y aeropuertos, fronteras y costas?', o:['La Guardia Civil.','La Policía local.','La Policía Nacional.'], c:0 },
  { id:'n1078', tema:'tarea1', p:'¿Quién hace el control de pasaportes en las fronteras de España?', o:['La Guardia Civil.','La Policía local.','La Policía Nacional.'], c:2 },
  { id:'n1079', tema:'tarea1', p:'¿Cuál de los siguientes políticos ha sido presidente del Gobierno en España?', o:['Manuel Fraga.','José María Aznar.','Yolanda Díaz.'], c:1 },
  { id:'n1080', tema:'tarea1', p:'¿Cómo se llama la policía autonómica de Cataluña?', o:['Guardia Civil.','Ertzaintza.','Mossos d\'Esquadra.'], c:2 },
  { id:'n1081', tema:'tarea1', p:'¿Cómo se llama la policía autonómica del País Vasco?', o:['Ertzaintza.','Guardia Civil.','Mossos d\'Esquadra.'], c:0 },
  { id:'n1082', tema:'tarea1', p:'¿Desde qué año es rey Felipe VI?', o:['Desde 1975.','Desde 2014.','Desde 2020.'], c:1 },
  { id:'n1083', tema:'tarea1', p:'¿Quién regula el tráfico en los pueblos y ciudades?', o:['La Guardia Civil.','Protección Civil.','La Policía Local.'], c:2 },
  { id:'n1084', tema:'tarea1', p:'¿Quién puede presentar una queja al Defensor del Pueblo?', o:['Solo los ciudadanos legalmente residentes.','Solo los españoles mayores de 18 años.','Todos los ciudadanos, españoles o extranjeros.'], c:2 },
  { id:'n1085', tema:'tarea1', p:'En España el voto en las elecciones es…', o:['un derecho.','un deber.','una obligación.'], c:0 },
  { id:'n1086', tema:'tarea1', p:'¿Quién vigila el tráfico en las carreteras?', o:['La Guardia Civil.','La Policía Nacional.','El Ejército de Tierra.'], c:0 },
  { id:'n1087', tema:'tarea1', p:'¿Qué organismo se encarga de recaudar los impuestos?', o:['El Tribunal de Cuentas.','La Agencia Tributaria.','El Consejo Económico y Social.'], c:1 },
  { id:'n1088', tema:'tarea1', p:'¿Dónde se publican las leyes nacionales?', o:['En el boletín del Instituto Nacional de Estadística (INE).','En el Portal de la Administración Electrónica (PAe).','En el Boletín Oficial del Estado (BOE).'], c:2 },
  { id:'n1089', tema:'tarea1', p:'¿Cómo se llaman los órganos de gobierno que solo existen en Canarias?', o:['Cabildos.','Consejos insulares.','Diputaciones.'], c:0 },
  { id:'n1090', tema:'tarea1', p:'¿Cuál de estos trámites administrativos puede realizarse en la sede electrónica?', o:['Tramitar el DNI.','Renovar el pasaporte.','Pagar los impuestos.'], c:2 },
  { id:'n1091', tema:'tarea1', p:'¿Cuál es el número de teléfono de información de la Administración General del Estado?', o:['010.','060.','091.'], c:1 },
  { id:'n1092', tema:'tarea1', p:'España está organizada en…', o:['cantones.','comunidades autónomas.','estados federales.'], c:1 },
  { id:'n1093', tema:'tarea1', p:'¿Cuántos partidos políticos hay en España?', o:['Ninguno.','Uno.','Muchos.'], c:2 },
  { id:'n1094', tema:'tarea1', p:'¿Dónde tiene lugar la investidura del presidente del Gobierno?', o:['En el Palacio de la Moncloa.','En el Congreso de los Diputados.','En el Senado.'], c:1 },
  { id:'n1095', tema:'tarea1', p:'¿Quién tiene el mando supremo de las Fuerzas Armadas?', o:['El rey.','El presidente del Gobierno.','El ministro de Defensa.'], c:0 },
  { id:'n1096', tema:'tarea1', p:'¿Quién es el representante del Estado en una comunidad autónoma?', o:['El presidente de la comunidad autónoma.','El delegado del Gobierno.','El presidente de la Asamblea autonómica.'], c:1 },
  { id:'n1097', tema:'tarea1', p:'¿Cuántas provincias hay en España?', o:['45.','50.','55.'], c:1 },
  { id:'n1098', tema:'tarea1', p:'La enseñanza de las lenguas cooficiales es competencia…', o:['del Estado.','de la comunidad autónoma.','de la provincia.'], c:1 },
  { id:'n1099', tema:'tarea1', p:'El poder ejecutivo corresponde…', o:['al Gobierno del Estado.','al Congreso y al Senado.','a los jueces y magistrados.'], c:0 },
  { id:'n1100', tema:'tarea1', p:'¿Cuántas cámaras hay en el Parlamento español?', o:['Una.','Dos.','Tres.'], c:1 },
  { id:'n1101', tema:'tarea1', p:'El suministro de agua y el alumbrado de las ciudades es competencia de…', o:['el ayuntamiento.','el Gobierno autonómico.','el Ministerio de Obras Públicas y Urbanismo.'], c:0 },
  { id:'n1102', tema:'tarea1', p:'En materias como nacionalidad, inmigración, emigración o extranjería solo tiene competencia…', o:['el Estado.','las comunidades autónomas.','los ayuntamientos.'], c:0 },
  { id:'n1103', tema:'tarea1', p:'¿Cuántas mujeres han sido presidentas de Gobierno en España?', o:['Ninguna.','Una.','Dos.'], c:0 },
  { id:'n1104', tema:'tarea1', p:'Las relaciones internacionales son competencia de…', o:['el Estado.','las comunidades autónomas.','los ayuntamientos.'], c:0 },
  { id:'n1105', tema:'tarea1', p:'El Ayuntamiento está formado por el alcalde y…', o:['los concejales.','los diputados.','los senadores.'], c:0 },
  { id:'n1106', tema:'tarea1', p:'¿Quiénes forman el gobierno de las comunidades autónomas?', o:['El presidente y los ministros.','El alcalde y los concejales.','El presidente y los consejeros.'], c:2 },
  { id:'n1107', tema:'tarea1', p:'¿Cuál es el órgano de gobierno en los municipios?', o:['El ayuntamiento.','La diputación.','El cabildo.'], c:0 },
  { id:'n1108', tema:'tarea1', p:'¿Cómo se llaman los órganos de gobierno de las provincias españolas?', o:['Cabildos.','Consejos insulares.','Diputaciones.'], c:2 },
  { id:'n1109', tema:'tarea1', p:'¿Cuál es el órgano superior del poder ejecutivo?', o:['El Gobierno.','Las Fuerzas Armadas.','Las Cortes Generales.'], c:0 },
  { id:'n1110', tema:'tarea1', p:'El idioma español también se llama…', o:['aragonés.','castellano.','leonés.'], c:1 },
  { id:'n1111', tema:'tarea1', p:'¿A quiénes se elige en las elecciones al Parlamento Europeo?', o:['A los ministros europeos.','A los consejeros delegados.','A los eurodiputados.'], c:2 },
  { id:'n1112', tema:'tarea1', p:'Los españoles pueden votar a partir de los…', o:['16 años.','18 años.','21 años.'], c:1 },
  { id:'n1113', tema:'tarea1', p:'Algunos ciudadanos extranjeros pueden votar en las elecciones…', o:['municipales.','autonómicas.','generales.'], c:0 },
  { id:'n1114', tema:'tarea1', p:'¿Quién controla la gestión financiera del Estado?', o:['El Banco de España.','La Agencia Tributaria.','El Tribunal de Cuentas.'], c:2 },
  { id:'n1115', tema:'tarea1', p:'¿A quiénes se elige en las elecciones generales?', o:['A los senadores y diputados.','A los eurodiputados.','A los concejales.'], c:0 },
  { id:'n1116', tema:'tarea1', p:'¿Cuántos miembros tiene el Congreso de los Diputados?', o:['300.','350.','400.'], c:1 },
  { id:'n1117', tema:'tarea1', p:'Los municipios y provincias forman parte de la Administración…', o:['autonómica.','local.','central.'], c:1 },
  { id:'n1118', tema:'tarea1', p:'La comunidad autónoma más poblada de España es…', o:['Andalucía.','Cataluña.','Castilla y León.'], c:0 },
  { id:'n1119', tema:'tarea1', p:'¿Cómo se llama la organización que defiende los intereses de los trabajadores?', o:['Asociación.','Partido.','Sindicato.'], c:2 },
  { id:'n1120', tema:'tarea1', p:'¿Quién elige al presidente del Gobierno?', o:['El Congreso de los Diputados.','El rey.','El Tribunal Supremo.'], c:0 },

  /* ── TAREA2: Derechos y deberes fundamentales (36 preguntas) ── */

  { id:'n2001', tema:'tarea2', p:'En España, la Constitución obliga a todos los ciudadanos a practicar una religión.', o:['Verdadero.','Falso.'], c:1, vf:false, corr:'La Constitución garantiza la libertad ideológica y religiosa: nadie está obligado a practicar ninguna religión.' },
  { id:'n2002', tema:'tarea2', p:'Los españoles que obtienen la nacionalidad por residencia deben esperar tres años para poder votar en las elecciones.', o:['Verdadero.','Falso.'], c:1, vf:false, corr:'Pueden votar desde que son españoles: tienen derecho al voto todos los españoles mayores de 18 años, sin ningún periodo de espera.' },
  { id:'n2003', tema:'tarea2', p:'En España, la Constitución prohíbe la tortura y la pena de muerte.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2004', tema:'tarea2', p:'El funcionamiento de los partidos políticos tiene que ser democrático.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2005', tema:'tarea2', p:'Se puede obligar a alguien a decir cuáles son sus ideas políticas o religiosas.', o:['Verdadero.','Falso.'], c:1, vf:false, corr:'Nadie puede ser obligado a decir cuáles son sus ideas políticas o religiosas.' },
  { id:'n2006', tema:'tarea2', p:'Se puede limitar a una persona el derecho a entrar y salir libremente de España por motivos ideológicos.', o:['Verdadero.','Falso.'], c:1, vf:false, corr:'Los españoles pueden entrar y salir de España sin que ese derecho pueda limitarse por motivos políticos o ideológicos.' },
  { id:'n2007', tema:'tarea2', p:'La Educación Primaria (de 6 a 12 años) es gratuita y obligatoria.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2008', tema:'tarea2', p:'La Constitución garantiza el derecho de los españoles a una vivienda digna.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2009', tema:'tarea2', p:'En España la policía puede entrar en cualquier casa sin resolución judicial en cualquier momento.', o:['Verdadero.','Falso.'], c:1, vf:false, corr:'El domicilio es inviolable: la policía solo puede entrar con autorización judicial, con permiso del titular o cuando se está cometiendo un delito.' },
  { id:'n2010', tema:'tarea2', p:'Se garantiza el secreto de las comunicaciones de los españoles, salvo resolución judicial.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2011', tema:'tarea2', p:'La Constitución reconoce el derecho de los ciudadanos a asociarse libremente.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2012', tema:'tarea2', p:'Los profesores pueden enseñar con libertad, dentro de los límites de la Constitución.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2013', tema:'tarea2', p:'La Constitución reconoce únicamente los derechos fundamentales de los españoles.', o:['Verdadero.','Falso.'], c:1, vf:false, corr:'La Constitución recoge los derechos de los españoles dentro y fuera de España y también los de los residentes extranjeros.' },
  { id:'n2014', tema:'tarea2', p:'Los ciudadanos deben colaborar con los jueces si se lo piden.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2015', tema:'tarea2', p:'La ley limita el acceso de terceras personas a datos de carácter personal.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2016', tema:'tarea2', p:'La libertad de prensa está limitada por el respeto al honor de las personas.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2017', tema:'tarea2', p:'En España las causas de separación y divorcio están reguladas por la ley.', o:['Verdadero.','Falso'], c:0, vf:true },
  { id:'n2018', tema:'tarea2', p:'La atención sanitaria gratuita es solo para personas mayores de 65 años.', o:['Verdadero.','Falso.'], c:1, vf:false, corr:'La atención sanitaria pública es gratuita para todos, sin límite de edad.' },
  { id:'n2019', tema:'tarea2', p:'En España los hombres y las mujeres tienen los mismos derechos.', o:['Verdadero','Falso.'], c:0, vf:true },
  { id:'n2020', tema:'tarea2', p:'La enseñanza obligatoria consta de dos etapas: Educación Primaria y Educación Secundaria Obligatoria.', o:['Verdadero','Falso'], c:0, vf:true },
  { id:'n2021', tema:'tarea2', p:'En España hay una religión oficial.', o:['Verdadero.','Falso.'], c:1, vf:false, corr:'No hay ninguna religión oficial en España: es un Estado aconfesional.' },
  { id:'n2022', tema:'tarea2', p:'La atención sanitaria pública es gratuita.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2023', tema:'tarea2', p:'La enseñanza básica en España es solo para los extranjeros.', o:['Verdadero.','Falso.'], c:1, vf:false, corr:'La enseñanza básica es obligatoria y gratuita para todos, no solo para los extranjeros.' },
  { id:'n2024', tema:'tarea2', p:'En España está reconocido el derecho de asociación.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2025', tema:'tarea2', p:'Los sindicatos pueden participar en negociaciones con empresarios y con el Gobierno.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2026', tema:'tarea2', p:'Los trabajadores tienen derecho a hacer huelga.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2027', tema:'tarea2', p:'La libertad ideológica está garantizada solo en parte del territorio nacional.', o:['Verdadero.','Falso.'], c:1, vf:false, corr:'La libertad ideológica y religiosa está garantizada en todo el territorio nacional.' },
  { id:'n2028', tema:'tarea2', p:'Todos los ciudadanos tienen acceso al sistema de Seguridad Social público, excepto si están desempleados.', o:['Verdadero.','Falso.'], c:1, vf:false, corr:'Todos los ciudadanos tienen acceso a la Seguridad Social pública, especialmente quienes no tienen trabajo.' },
  { id:'n2029', tema:'tarea2', p:'Todos tienen derecho a disfrutar de un medio ambiente adecuado para el desarrollo de la persona, así como el deber de conservarlo.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2030', tema:'tarea2', p:'En España, los poderes públicos deben proteger la salud y promover el deporte.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2031', tema:'tarea2', p:'La enseñanza básica en España es obligatoria y gratuita.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2032', tema:'tarea2', p:'La ley prohíbe la discriminación por cualquier circunstancia personal o social.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2033', tema:'tarea2', p:'En España, los ciudadanos pueden desplazarse libremente por todo el territorio nacional.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2034', tema:'tarea2', p:'Los jueces administran la justicia en España según las indicaciones del Gobierno.', o:['Verdadero.','Falso.'], c:1, vf:false, corr:'Los jueces administran la justicia de forma independiente, no siguiendo indicaciones del Gobierno.' },
  { id:'n2035', tema:'tarea2', p:'Los españoles deben ayudar en los casos de catástrofe o calamidad pública.', o:['Verdadero.','Falso.'], c:0, vf:true },
  { id:'n2036', tema:'tarea2', p:'En España los ciudadanos pueden elegir en qué ciudad quieren vivir.', o:['Verdadero.','Falso.'], c:0, vf:true },

  /* ── TAREA3: Organización territorial de España. Geografía física y política (24 preguntas) ── */

  { id:'n3001', tema:'tarea3', p:'¿Dónde están Cáceres y Badajoz?', o:['En el Principado de Asturias.','En Andalucía.','En Extremadura.'], c:2 },
  { id:'n3002', tema:'tarea3', p:'¿Cuál es la capital la Comunidad Valenciana?', o:['Alicante.','Castellón.','Valencia.'], c:2 },
  { id:'n3003', tema:'tarea3', p:'¿Dónde están las islas Baleares?', o:['En el mar Cantábrico.','En el mar Mediterráneo.','En el océano Atlántico.'], c:1 },
  { id:'n3004', tema:'tarea3', p:'¿Cómo se llama la extensa llanura situada en el centro de la península ibérica?', o:['Marisma.','Cordillera.','Meseta.'], c:2 },
  { id:'n3005', tema:'tarea3', p:'El parque nacional de Ordesa está en...', o:['Aragón.','Navarra.','Castilla-La Mancha.'], c:0 },
  { id:'n3006', tema:'tarea3', p:'¿En qué comunidad autónoma están Guadalajara y Cuenca?', o:['En Castilla y León.','En Castilla-La Mancha.','En Cantabria.'], c:1 },
  { id:'n3007', tema:'tarea3', p:'¿Qué comunidad autónoma tiene como capital Santiago de Compostela?', o:['Galicia.','Asturias.','Cantabria.'], c:0 },
  { id:'n3008', tema:'tarea3', p:'¿Dónde está Almería?', o:['En Andalucía.','En Canarias.','En Aragón.'], c:0 },
  { id:'n3009', tema:'tarea3', p:'La capital de la comunidad autónoma de Galicia es…', o:['A Coruña.','Vigo.','Santiago de Compostela.'], c:2 },
  { id:'n3010', tema:'tarea3', p:'¿Cuál de estos ríos desemboca en el mar Mediterráneo?', o:['El Tajo.','El Júcar.','El Duero.'], c:1 },
  { id:'n3011', tema:'tarea3', p:'¿Dónde está el monte Aneto?', o:['En los Pirineos.','En el Sistema Central.','En Sierra Nevada.'], c:0 },
  { id:'n3012', tema:'tarea3', p:'La ciudad de Vitoria es la sede administrativa de…', o:['Navarra.','País Vasco.','La Rioja.'], c:1 },
  { id:'n3013', tema:'tarea3', p:'España se divide en…', o:['departamentos y regiones.','comunidades y ciudades autónomas.','regiones autónomas y distritos.'], c:1 },
  { id:'n3014', tema:'tarea3', p:'El parque nacional de Aigüestortes está en...', o:['Cataluña.','Aragón','Castilla y León.'], c:0 },
  { id:'n3015', tema:'tarea3', p:'En el norte de África están Ceuta y…', o:['Almería.','Melilla.','Cádiz.'], c:1 },
  { id:'n3016', tema:'tarea3', p:'¿En qué lugar de España hay un clima que se caracteriza por inviernos fríos y veranos muy calurosos?', o:['Canarias.','Comunidad Valenciana.','Madrid.'], c:2 },
  { id:'n3017', tema:'tarea3', p:'¿Cuál de estos ríos desemboca en el océano Atlántico?', o:['El Guadalquivir.','El Manzanares.','El Júcar.'], c:0 },
  { id:'n3018', tema:'tarea3', p:'¿Cuál de estas provincias forma parte de la Comunidad de Castilla y León?', o:['Burgos.','Huesca.','Guadalajara.'], c:0 },
  { id:'n3019', tema:'tarea3', p:'¿En qué comunidad autónoma está la ciudad de Huesca?', o:['Castilla-La Mancha.','Aragón.','Extremadura.'], c:1 },
  { id:'n3020', tema:'tarea3', p:'Canarias tiene un clima…', o:['mediterráneo.','oceánico.','subtropical.'], c:2 },
  { id:'n3021', tema:'tarea3', p:'El principal río que desemboca en el mar Mediterráneo es el…', o:['Ebro.','Duero.','Tajo.'], c:0 },
  { id:'n3022', tema:'tarea3', p:'España está entre los países de Europa más…', o:['lluviosos.','montañosos.','fríos.'], c:1 },
  { id:'n3023', tema:'tarea3', p:'¿En qué provincia está el parque nacional de Monfragüe?', o:['En Cáceres.','En Murcia.','En Ciudad Real.'], c:0 },
  { id:'n3024', tema:'tarea3', p:'¿Cuál es la capital de la comunidad autónoma de Extremadura?', o:['Cáceres.','Badajoz.','Mérida.'], c:2 },

  /* ── TAREA4: Cultura e historia de España (36 preguntas) ── */

  { id:'n4001', tema:'tarea4', p:'Los personajes principales de la novela el Quijote son don Quijote y…', o:['Don Juan.','Sancho Panza.','Doña Inés.'], c:1 },
  { id:'n4002', tema:'tarea4', p:'¿Qué científica española es reconocida por sus investigaciones?', o:['Almudena Grandes.','Montserrat Caballé.','Margarita Salas.'], c:2 },
  { id:'n4003', tema:'tarea4', p:'¿Quién escribió La casa de Bernarda Alba?', o:['Federico García Lorca.','Miguel de Cervantes.','Antonio Machado.'], c:0 },
  { id:'n4004', tema:'tarea4', p:'¿Quién escribió Nada, una novela sobre la posguerra española?', o:['Carmen Laforet.','Ana María Matute.','María Dueñas.'], c:0 },
  { id:'n4005', tema:'tarea4', p:'¿Qué músico compuso El amor brujo?', o:['Manuel de Falla.','Isaac Albéniz.','Joaquín Rodrigo.'], c:0 },
  { id:'n4006', tema:'tarea4', p:'¿Qué es típico en la Noche de San Juan?', o:['Comer uvas.','Encender hogueras.','Regalar libros.'], c:1 },
  { id:'n4007', tema:'tarea4', p:'¿Cuál es el instrumento más característico de la música flamenca?', o:['La gaita.','La guitarra.','El piano.'], c:1 },
  { id:'n4008', tema:'tarea4', p:'Isabel Coixet es una…', o:['cantante pop.','bailarina clásica.','directora de cine.'], c:2 },
  { id:'n4009', tema:'tarea4', p:'Una de las cantantes españolas más famosas actualmente es...', o:['Rosalía.','Marisol.','Lola Flores.'], c:0 },
  { id:'n4010', tema:'tarea4', p:'¿En qué ciudad de España hay una mezquita que es Patrimonio de la Humanidad?', o:['Santiago de Compostela.','Madrid.','Córdoba.'], c:2 },
  { id:'n4011', tema:'tarea4', p:'¿En qué ciudad de España se encuentra La Alhambra, que es Patrimonio de la Humanidad?', o:['En Sevilla.','En Córdoba.','En Granada.'], c:2 },
  { id:'n4012', tema:'tarea4', p:'¿Cuál es el nombre de la directora española que ha destacado por su mirada crítica y por modernizar el cine nacional?', o:['Pilar Miró.','Sara Baras.','Penélope Cruz.'], c:0 },
  { id:'n4013', tema:'tarea4', p:'¿Qué novela de éxito ha escrito Irene Vallejo?', o:['El infinito en un junco.','El tiempo entre costuras.','El camino.'], c:0 },
  { id:'n4014', tema:'tarea4', p:'¿Cómo se llama la mayor institución pública dedicada a la investigación en España?', o:['Real Academia Española (RAE).','Consejo Superior de investigaciones Científicas (CSIC).','La sociedad General de Autores (SGAE).'], c:1 },
  { id:'n4015', tema:'tarea4', p:'Paco de Lucía fue un famoso….', o:['científico.','guitarrista.','pintor.'], c:1 },
  { id:'n4016', tema:'tarea4', p:'¿Qué celebramos el 24 de diciembre?', o:['Carnaval.','Nochebuena.','San Juan.'], c:1 },
  { id:'n4017', tema:'tarea4', p:'Juan Mari Arzak es un famoso....', o:['escritor.','músico','cocinero.'], c:2 },
  { id:'n4018', tema:'tarea4', p:'¿Quién fue Clara Campoamor?', o:['Una defensora de los derechos de la mujer.','Una cantante lírica.','Una directora de cine.'], c:0 },
  { id:'n4019', tema:'tarea4', p:'¿Qué canciones típicas se cantan en Navidad?', o:['Flamenco.','Villancicos.','Jotas.'], c:1 },
  { id:'n4020', tema:'tarea4', p:'La Liga y la Copa del Rey son competiciones de…', o:['natación.','atletismo.','fútbol.'], c:2 },
  { id:'n4021', tema:'tarea4', p:'¿Quién ha recibido el premio Nobel de Literatura?', o:['María Zambrano.','Pablo Picasso.','Vicente Aleixandre.'], c:2 },
  { id:'n4022', tema:'tarea4', p:'¿Qué fiesta se celebra en Pamplona el 7 de julio?', o:['Los sanfermines.','Las Fallas.','La Feria de Abril.'], c:0 },
  { id:'n4023', tema:'tarea4', p:'Teresa Perales y Daniel Molina son...', o:['campeones paraolímpicos.','músicos famosos.','artistas de cine.'], c:0 },
  { id:'n4024', tema:'tarea4', p:'¿Qué toman los españoles la noche del 31 de diciembre para celebrar el cambio de año?', o:['Lentejas.','Uvas.','Aceitunas.'], c:1 },
  { id:'n4025', tema:'tarea4', p:'¿Qué mujer es autora del cuadro La verbena?', o:['Maruja Mallo.','Carmen Maura.','Clara Lago.'], c:0 },
  { id:'n4026', tema:'tarea4', p:'¿En qué museo español puedes ver el cuadro Guernica de Picasso?', o:['Museo del Prado.','Museo Reina Sofía.','Museo Thyssen-Bornemisza.'], c:1 },
  { id:'n4027', tema:'tarea4', p:'¿Qué escritora española escribe en otra lengua oficial de España?', o:['Mercè Rodoreda.','Almudena Grandes.','Ana María Matute.'], c:0 },
  { id:'n4028', tema:'tarea4', p:'¿Qué tres culturas convivieron en la España medieval?', o:['La cristiana, la judía y la musulmana.','La fenicia, la judía y la musulmana.','La griega, la cristiana y la judía.'], c:0 },
  { id:'n4029', tema:'tarea4', p:'El 6 de diciembre se celebra en España…', o:['el Día de la Constitución.','la llegada de Colón a América.','el Día del Libro.'], c:0 },
  { id:'n4030', tema:'tarea4', p:'¿Qué ciudad fue un centro científico en Al-Ándalus, donde se estudiaba medicina y astronomía?', o:['Barcelona.','Madrid.','Córdoba.'], c:2 },
  { id:'n4031', tema:'tarea4', p:'¿En qué ciudad española está el Museo Guggenheim?', o:['Bilbao.','Madrid.','Valencia.'], c:0 },
  { id:'n4032', tema:'tarea4', p:'El Premio Cervantes se da a…', o:['actores.','escritores.','pintores.'], c:1 },
  { id:'n4033', tema:'tarea4', p:'¿Qué premio reconoce a los mejores actores y películas?', o:['Premio Goya.','Premio Nobel.','Premio Cervantes.'], c:0 },
  { id:'n4034', tema:'tarea4', p:'¿Qué premios promueven en España valores científicos, culturales y humanísticos?', o:['Los Premios Cervantes.','Los Premios Princesa de Asturias.','Los Premios Goya.'], c:1 },
  { id:'n4035', tema:'tarea4', p:'¿Cuál de estos deportes es muy popular en España?', o:['El fútbol.','El esquí','El golf.'], c:0 },
  { id:'n4036', tema:'tarea4', p:'¿Cuál de estos deportistas juega al tenis?', o:['Pau Gasol.','Carlos Sainz.','Carlos Alcaraz.'], c:2 },

  /* ── TAREA5: Sociedad española (84 preguntas) ── */

  { id:'n5001', tema:'tarea5', p:'¿Qué documento deben solicitar los extranjeros para residir legalmente en España?', o:['El Documento Nacional de Identidad (DNI).','La Tarjeta de Identidad de Extranjero (TIE).','El certificado de empadronamiento.'], c:1 },
  { id:'n5002', tema:'tarea5', p:'¿Cuál es el documento que certifica el lugar de residencia del titular?', o:['El certificado de empadronamiento.','La partida de nacimiento.','El carné de conducir.'], c:0 },
  { id:'n5003', tema:'tarea5', p:'¿A qué sustituye el registro electrónico individual?', o:['Al DNI.','Al permiso de conducir.','Al libro de familia.'], c:2 },
  { id:'n5004', tema:'tarea5', p:'¿Cuál es la edad mínima para conducir un coche en España?', o:['16 años.','18 años.','20 años.'], c:1 },
  { id:'n5005', tema:'tarea5', p:'El carné de conducir se hace en…', o:['la Dirección General de Tráfico (DGT).','la Policía Nacional.','el Registro Civil.'], c:0 },
  { id:'n5006', tema:'tarea5', p:'Para sacar el carné de conducir hay que aprobar…', o:['un examen teórico.','un examen práctico.','un examen teórico y otro práctico.'], c:2 },
  { id:'n5007', tema:'tarea5', p:'¿Dónde se tramita el libro de familia?', o:['En el Registro Civil.','En la Seguridad Social.','En las comisarías de policía.'], c:0 },
  { id:'n5008', tema:'tarea5', p:'¿Cuál de estos canales de televisión es autonómico?', o:['Telecinco.','Nova.','Canal Sur.'], c:2 },
  { id:'n5009', tema:'tarea5', p:'¿Cuánto dura el permiso de maternidad o paternidad?', o:['12 semanas.','16 semanas.','22 semanas.'], c:1 },
  { id:'n5010', tema:'tarea5', p:'¿Cuál es la tasa máxima de alcohol en sangre permitida a los conductores, en gramos por litro (g/l)?', o:['0,5.','0,7.','0,9.'], c:0 },
  { id:'n5011', tema:'tarea5', p:'¿Cuál es el tipo de residencia más habitual en España?', o:['Casa rural.','Piso en un edificio de viviendas.','Chalé independiente.'], c:1 },
  { id:'n5012', tema:'tarea5', p:'¿Qué comunidad autónoma es conocida por la calidad de su aceite de oliva?', o:['Cantabria.','Andalucía.','La Rioja.'], c:1 },
  { id:'n5013', tema:'tarea5', p:'¿Cómo se llama la revisión que deben pasar obligatoriamente los coches?', o:['IBI (Impuesto sobre Bienes Inmuebles).','ITV (Inspección Técnica de Vehículos).','ITE (Inspección Técnica de Edificios).'], c:1 },
  { id:'n5014', tema:'tarea5', p:'El aperitivo que acompaña a la bebida en bares y restaurantes se llama...', o:['bocadillo.','tapa.','primer plato.'], c:1 },
  { id:'n5015', tema:'tarea5', p:'¿Dónde se tramita la tarjeta sanitaria?', o:['En la comisaría de policía.','En el centro de salud.','En el Ministerio de Sanidad.'], c:1 },
  { id:'n5016', tema:'tarea5', p:'¿Con cuántos hijos una familia es numerosa?', o:['Con 1 hijo.','Con 2 hijos.','Con 3 hijos.'], c:2 },
  { id:'n5017', tema:'tarea5', p:'En España está permitido el matrimonio…', o:['solo entre personas del mismo sexo.','entre personas del mismo y diferente sexo.','solo entre personas de diferente sexo.'], c:1 },
  { id:'n5018', tema:'tarea5', p:'Los propietarios de perros deben registrarlos en…', o:['el Ministerio de Justicia.','la comisaría de policía.','el Ayuntamiento.'], c:2 },
  { id:'n5019', tema:'tarea5', p:'Los principales ingredientes de la tortilla española son huevos y…', o:['pimientos.','patatas.','tomates.'], c:1 },
  { id:'n5020', tema:'tarea5', p:'¿Cuál es uno de los platos más conocidos internacionalmente de la gastronomía española?', o:['Gazpacho.','Pizza.','Pasta.'], c:0 },
  { id:'n5021', tema:'tarea5', p:'¿Cuál de estos canales de televisión es público?', o:['Tele 5.','La 1.','Antena 3.'], c:1 },
  { id:'n5022', tema:'tarea5', p:'En una comunidad de vecinos, una de las normas es…', o:['abrir la puerta al cartero.','no molestar con ruido.','limpiar los espacios comunes.'], c:1 },
  { id:'n5023', tema:'tarea5', p:'¿Cuál de estos es el principal ingrediente de la paella valenciana?', o:['Arroz.','Chorizo.','Garbanzos.'], c:0 },
  { id:'n5024', tema:'tarea5', p:'La sidra es una bebida típica de…', o:['Asturias.','Valencia.','Canarias.'], c:0 },
  { id:'n5025', tema:'tarea5', p:'Los españoles tienen dos apellidos, el primero es…', o:['obligatoriamente el de la madre.','obligatoriamente el del padre.','puede ser el de la madre o el del padre.'], c:2 },
  { id:'n5026', tema:'tarea5', p:'La Fiesta Nacional de España es el…', o:['6 de diciembre.','15 de agosto.','12 de octubre.'], c:2 },
  { id:'n5027', tema:'tarea5', p:'¿Qué días suelen cerrar la mayoría de las tiendas o el pequeño comercio?', o:['Los lunes.','Los domingos.','Los sábados por la tarde.'], c:1 },
  { id:'n5028', tema:'tarea5', p:'¿Dónde se hace el pasaporte?', o:['En el registro civil.','En una comisaría de policía.','En el Ayuntamiento.'], c:1 },
  { id:'n5029', tema:'tarea5', p:'El Ministerio de Igualdad es el encargado de luchar contra la violencia de género y la…', o:['separación.','discriminación.','solidaridad.'], c:1 },
  { id:'n5030', tema:'tarea5', p:'¿Qué comunidad autónoma es conocida por la calidad de sus cavas?', o:['Galicia.','Cataluña.','Castilla-La Mancha.'], c:1 },
  { id:'n5031', tema:'tarea5', p:'¿Qué documento se necesita para recibir atención médica en la sanidad pública?', o:['El pasaporte.','La tarjeta sanitaria.','El certificado de nacimiento.'], c:1 },
  { id:'n5032', tema:'tarea5', p:'El horario de Canarias, con respecto a la Península, es de…', o:['dos horas menos.','una hora menos.','una hora más.'], c:1 },
  { id:'n5033', tema:'tarea5', p:'Para acceder a la Universidad se debe superar una prueba de evaluación llamada…', o:['Selectividad.','Examen preuniversitario.','Prueba de Acceso a la Universidad.'], c:2 },
  { id:'n5034', tema:'tarea5', p:'¿Cuál de estos productos necesita importar España de otros países?', o:['Petróleo.','Aceite de oliva.','Medicamentos.'], c:0 },
  { id:'n5035', tema:'tarea5', p:'¿Qué tipo de impuestos tienen que pagar los ciudadanos en España?', o:['Impuestos directos como el IRPF.','Impuestos indirectos como el IVA.','Impuestos directos e indirectos.'], c:2 },
  { id:'n5036', tema:'tarea5', p:'Los adultos sin Bachillerato pueden estudiar en la Universidad haciendo una prueba especial a partir de los…', o:['18 años.','23 años.','25 años.'], c:2 },
  { id:'n5037', tema:'tarea5', p:'¿Dónde puede encontrarse la siguiente norma «No pisar el césped, ni arrancar flores»?', o:['En zonas de recreo.','En los teatros.','En los estadios de fútbol.'], c:0 },
  { id:'n5038', tema:'tarea5', p:'El Bachillerato en España…', o:['es obligatorio.','se compone de dos cursos académicos.','es la enseñanza a alumnos de 14 a 16 años.'], c:1 },
  { id:'n5039', tema:'tarea5', p:'El Impuesto sobre el Valor Añadido (IVA) forma parte de los…', o:['Impuestos indirectos.','Impuestos sobre la renta.','Impuestos sobre sociedades.'], c:0 },
  { id:'n5040', tema:'tarea5', p:'¿Qué número reciben los trabajadores al comenzar su primer empleo?', o:['El de la Seguridad Social.','El del pasaporte.','El número de servicio.'], c:0 },
  { id:'n5041', tema:'tarea5', p:'Los colegios públicos…', o:['pueden decidir su número de plazas.','pueden contratar a los profesores que quieran.','son gratuitos.'], c:2 },
  { id:'n5042', tema:'tarea5', p:'¿Cuál de estos puertos es uno de los principales de España?', o:['Tenerife.','Alicante.','Algeciras.'], c:2 },
  { id:'n5043', tema:'tarea5', p:'Un colegio concertado es un colegio privado que…', o:['recibe dinero de la Administración.','financian los padres de los alumnos.','recibe dinero de los bancos.'], c:0 },
  { id:'n5044', tema:'tarea5', p:'España exporta productos principalmente a países…', o:['de Hispanoamérica.','de la Unión Europea.','del norte de África.'], c:1 },
  { id:'n5045', tema:'tarea5', p:'Las bibliotecas públicas son gratuitas para…', o:['todos.','los parados.','los niños.'], c:0 },
  { id:'n5046', tema:'tarea5', p:'¿Cuál de estos productos exporta España más que importa?', o:['Gas.','Ropa.','Calzado.'], c:2 },
  { id:'n5047', tema:'tarea5', p:'Una persona mayor de 18 años puede obtener el título de Graduado en Educación Secundaria Obligatoria en…', o:['un Centro de Educación de Personas Adultas.','un centro de enseñanza primaria.','una universidad.'], c:0 },
  { id:'n5048', tema:'tarea5', p:'La formación profesional…', o:['es para mayores de 25 años.','puede ser de grado medio o superior.','es obligatoria.'], c:1 },
  { id:'n5049', tema:'tarea5', p:'¿Adónde vamos para ver al médico de familia o al pediatra?', o:['Al hospital.','Al centro de salud.','A la farmacia.'], c:1 },
  { id:'n5050', tema:'tarea5', p:'¿Para cuántos años vale la tarjeta sanitaria europea?', o:['Para un año.','Para dos años.','Para 10 años.'], c:1 },
  { id:'n5051', tema:'tarea5', p:'¿A qué hora se cena normalmente en España?', o:['A las 18 h.','A las 23 h.','A las 21 o 22 h.'], c:2 },
  { id:'n5052', tema:'tarea5', p:'¿Cuál es el número de teléfono único para cualquier emergencia?', o:['060.','112.','911.'], c:1 },
  { id:'n5053', tema:'tarea5', p:'¿Cuál de estos periódicos se publica a nivel nacional?', o:['El Diario Vasco.','El País.','La Voz de Galicia.'], c:1 },
  { id:'n5054', tema:'tarea5', p:'¿Dónde se venden sellos y tabaco?', o:['En el quiosco.','En la farmacia.','En el estanco.'], c:2 },
  { id:'n5055', tema:'tarea5', p:'¿Cuándo se puede llamar al número de teléfono para atención a víctimas de violencia de género?', o:['Las 24 horas del día.','En horario de mañana.','De lunes a viernes.'], c:0 },
  { id:'n5056', tema:'tarea5', p:'La organización que trabaja para conseguir la integración de las personas con discapacidad visual es…', o:['la ONCE.','Unicef.','Cáritas.'], c:0 },
  { id:'n5057', tema:'tarea5', p:'El Camino de Santiago es…', o:['Patrimonio de la Humanidad.','una vía de ferrocarril.','una ruta para excursionistas.'], c:0 },
  { id:'n5058', tema:'tarea5', p:'¿Cuál es el canal de televisión estatal que transmite noticias de actualidad nacional e internacional continuamente?', o:['Teledeporte.','La 1.','Canal 24 horas.'], c:2 },
  { id:'n5059', tema:'tarea5', p:'El teléfono gratuito para las víctimas de violencia de género es el…', o:['091.','112.','016.'], c:2 },
  { id:'n5060', tema:'tarea5', p:'En España, la red de trenes puede ser de larga distancia, de media distancia y…', o:['de cercanías.','rural.','transnacional.'], c:0 },
  { id:'n5061', tema:'tarea5', p:'¿Qué está prohibido en la puerta de un colegio?', o:['Fumar un cigarrillo.','Conducir un coche.','Vender refrescos.'], c:0 },
  { id:'n5062', tema:'tarea5', p:'¿Qué título se obtiene al finalizar un ciclo de grado medio de Formación Profesional?', o:['Bachiller.','Técnico.','Graduado en ESO.'], c:1 },
  { id:'n5063', tema:'tarea5', p:'¿Qué título se obtiene tras realizar una tesis doctoral en España?', o:['Máster.','Graduado.','Doctor.'], c:2 },
  { id:'n5064', tema:'tarea5', p:'¿Dónde se compran las medicinas con receta?', o:['En el hospital','En el centro de salud.','En la farmacia.'], c:2 },
  { id:'n5065', tema:'tarea5', p:'¿Cuál de estas tres recomendaciones podemos encontrar en un parque?', o:['No pisar el césped.','Se recomienda pagar el billete con el dinero justo.','Respetar las normas sobre equipaje.'], c:0 },
  { id:'n5066', tema:'tarea5', p:'¿Cuál de las siguientes cosas es obligatoria para el propietario de un coche en España?', o:['El garaje','El seguro.','La alarma.'], c:1 },
  { id:'n5067', tema:'tarea5', p:'El aeropuerto Adolfo Suárez está en…', o:['Barcelona.','Madrid','Bilbao.'], c:1 },
  { id:'n5068', tema:'tarea5', p:'En un coche es obligatorio el uso del cinturón de seguridad...', o:['solo en el asiento del conductor.','en los asientos delanteros.','en todos los asientos.'], c:2 },
  { id:'n5069', tema:'tarea5', p:'¿Cuál es el límite de velocidad en autopista?', o:['90 km/h.','120 km/h.','150 km/h.'], c:1 },
  { id:'n5070', tema:'tarea5', p:'Ceder el asiento a las personas con movilidad reducida es una norma que encontramos indicada en…', o:['el transporte público.','las bibliotecas.','los museos.'], c:0 },
  { id:'n5071', tema:'tarea5', p:'¿Cuál es el medio de transporte público que tiene una luz verde encendida si está libre?', o:['El autobús.','El taxi.','El tranvía.'], c:1 },
  { id:'n5072', tema:'tarea5', p:'¿Qué debes hacer si tienes un perro?', o:['Pasearlo sin correa.','Ponerle un microchip y vacunarlo','No recoger sus excrementos.'], c:1 },
  { id:'n5073', tema:'tarea5', p:'Los españoles necesitan el pasaporte para viajar a…', o:['Italia.','China.','Alemania.'], c:1 },
  { id:'n5074', tema:'tarea5', p:'¿Cuál es la edad mínima para trabajar en España?', o:['16 años.','18 años.','21 años.'], c:0 },
  { id:'n5075', tema:'tarea5', p:'¿Cuál es el sector de mayor peso en la economía española?', o:['Agricultura.','Servicios.','Construcción.'], c:1 },
  { id:'n5076', tema:'tarea5', p:'España es innovadora en el sector de…', o:['la ingeniería aeroespacial.','las energías renovables.','la energía nuclear.'], c:1 },
  { id:'n5077', tema:'tarea5', p:'¿Cómo se llama la ley laboral más importante de España?', o:['La Constitución.','El Estatuto de los Trabajadores.','El Servicio Público de Empleo Estatal.'], c:1 },
  { id:'n5078', tema:'tarea5', p:'¿Cuál de estos establecimientos está abierto 24 horas si es necesario?', o:['Farmacia.','Pescadería.','Librería.'], c:0 },
  { id:'n5079', tema:'tarea5', p:'La educación infantil en España…', o:['es obligatoria.','tiene dos ciclos.','empieza a los 4 años.'], c:1 },
  { id:'n5080', tema:'tarea5', p:'¿Cuándo empieza el calendario escolar?', o:['En agosto.','En septiembre.','En octubre.'], c:1 },
  { id:'n5081', tema:'tarea5', p:'Las Escuelas Oficiales de Idiomas…', o:['son centros de enseñanza privada.','son para mayores de 16 años.','dependen del Instituto Cervantes.'], c:1 },
  { id:'n5082', tema:'tarea5', p:'¿Cuál es el documento que recoge los años de cotización a la Seguridad Social?', o:['Informe de vida laboral.','Recibo de finiquito.','Certificado de profesionalidad.'], c:0 },
  { id:'n5083', tema:'tarea5', p:'Los convenios colectivos de una empresa son los que se firman con los representantes de los trabajadores sobre…', o:['las condiciones laborales.','el futuro de la empresa.','la relación con los clientes.'], c:0 },
  { id:'n5084', tema:'tarea5', p:'¿En cuál de estos sectores destaca España?', o:['En el turismo.','En la industria automovilística.','En tecnología digital.'], c:0 },

];
